[package]
name = "easy-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.8.0"
chrono = "0.4.31"
serde = "1.0.195"
serde_json = "1.0.87"
